### ISSUE TITLE
Running ./get_ffhq_aging.sh is giving us black/greyscale masks/parsings

### ISSUE THREAD

**Issue by ctsrkrk** [royorel/FFHQ-Aging-Dataset#8]
Hi 
When we run ./get_ffhq_aging.sh
and in this file we made some changes as below:
```
python download_ffhq_aging.py --resolution 256 --debug --num_threads 8 
CUDA_VISIBLE_DEVICES=0 python run_deeplab.py --resolution 256
```
When we ran this code we got parsings for 50 images
While the masks seen in the repo's readme have all the facial regions properly segmented in color, the parsings we generated were greyscale and it seems that different facial zones aren't properly segmented. Specifically, we see the lips, eyebrows , neck, eyes and hair differentiated but like the nose , eyes and many other facial zones are not segmented properly.

Please lets us know what we should do in this case
Thanks

**Comment by royorel** [comment]
Hi @ctsrkrk 

The run_deeplab.py code does not save a colored segmentation image. Instead it saves a label image where each pixel contains the label number. In order to get the colored images like you see in the readme file you should run a script similar to this one 
https://github.com/switchablenorms/CelebAMask-HQ/blob/master/face_parsing/Data_preprocessing/g_color.py 
on the deeplab outputs.

This is the script we used to generate the image you see in the readme file.

Roy

**Comment by glorioustory** [comment]
@royorel HI
If I don't generate colored images, I use black/gray images directly, will it affect the result in  Lifespan Age Transformation Synthesis?

**Comment by royorel** [comment]
@glorioustory 

Do you want to use the pre-trained model? or are you going to retrain from scratch?

If you plan to retrain with grayscale images, then I don't think it would be an issue. If you plan to use a pre-trained model Then I there's a chance the results will be affected because the model was only trained with color images.

**Comment by glorioustory** [comment]
@royorel 
thanks for your reply, I want to retrain from the beginning.
